In [1]:
import numpy as np

In [2]:
list1 = [1,2,3,4,5,6]
list2 = [7,6,8,9,1,5]
list3 = []
for i in range(len(list1)):
    add = list1[i] + list2[i]
    list3.append(add)
print(list3)

[8, 8, 11, 13, 6, 11]


In [3]:
array1 = np.array(list1)
array2 = np.array(list2)
array4 = np.array([88,45,23,21,55,27])
array3 = array1 + array2 + array4
array3

array([96, 53, 34, 34, 61, 38])

In [4]:
# shape (rows,columns)

array1.shape

(6,)

In [5]:
my_array = np.array(([1,3,5,6,7],[6,9,6,8,5]))
my_array.shape

(2, 5)

In [6]:
array1.ndim

1

In [7]:
my_array.ndim

2

In [8]:
array1.dtype

dtype('int32')

In [9]:
array4 = np.array([88,45,23,21,55,27], dtype=np.float32)
array4.dtype

dtype('float32')

In [10]:
array4

array([88., 45., 23., 21., 55., 27.], dtype=float32)

In [11]:
zero_array = np.zeros((4,6))
zero_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
zero_array.ndim

2

In [13]:
random_array = np.arange(12)
random_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
reshape_array = random_array.reshape(6,2)

In [15]:
reshape_array.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [16]:
reshape_array.reshape(12,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
ones_array = np.ones((3,9))
ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [18]:
new_arr = np.arange(20)
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
new_arr[5]

5

In [20]:
my_arr = np.array([89,45,23,55,23,98,10,55])
my_arr[5]

98

In [21]:
my_arr[2:6]

array([23, 55, 23, 98])

In [22]:
my_arr[5] = 456

In [23]:
my_arr

array([ 89,  45,  23,  55,  23, 456,  10,  55])

In [24]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Broadcasting concept:
"Broadcasting in Python is like making different-size groups of numbers work together without changing their actual sizes. It helps do math with these groups smoothly, even when they're not the exact same size, by temporarily adjusting them behind the scenes."



In [25]:
new_arr *5 #Broadcasting

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [26]:
new_arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21])

In [ ]:
two_arr = np.array(([23,45,56],[34,67,92]))
two_arr

array([[23, 45, 56],
       [34, 67, 92]])

In [ ]:
two_arr *0

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
random_array = np.random.randn(4,3)
random_array

array([[ 0.76199901, -0.81474623, -0.0791762 ],
       [-0.68704345,  1.93978024,  2.42670007],
       [ 0.53819055, -0.33830554, -1.06808095],
       [ 0.96236076, -0.64338093, -0.87599171]])

In [ ]:
# boolean Indexing
data = np.array(['Bob','Joe','Will','Bob','Joe','Will','Joe','Will'])
data

array(['Bob', 'Joe', 'Will', 'Bob', 'Joe', 'Will', 'Joe', 'Will'],
      dtype='<U4')

In [ ]:
data == 'Bob'

array([ True, False, False,  True, False, False, False, False])

In [ ]:
data == 'Joe'

array([False,  True, False, False,  True, False,  True, False])

In [ ]:
random_array >= 1

array([[False, False, False],
       [False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [ ]:
# Fancy Indexing
empt_arr = np.empty((8,4), dtype = '<U4')
empt_arr

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U4')

In [ ]:
for i in range(8):
    empt_arr[i] = data[i]

In [ ]:
empt_arr

array([['Bob', 'Bob', 'Bob', 'Bob'],
       ['Joe', 'Joe', 'Joe', 'Joe'],
       ['Will', 'Will', 'Will', 'Will'],
       ['Bob', 'Bob', 'Bob', 'Bob'],
       ['Joe', 'Joe', 'Joe', 'Joe'],
       ['Will', 'Will', 'Will', 'Will'],
       ['Joe', 'Joe', 'Joe', 'Joe'],
       ['Will', 'Will', 'Will', 'Will']], dtype='<U4')

Concatenation:


In [ ]:
#concatenation
array_1 = np.array([2,3,4,6])
array_2 = np.array([6,9,4,6])
array_1

array([2, 3, 4, 6])

In [ ]:
array_2

array([6, 9, 4, 6])

In [ ]:
np.concatenate([array_1,array_2, data])

array(['2', '3', '4', '6', '6', '9', '4', '6', 'Bob', 'Joe', 'Will',
       'Bob', 'Joe', 'Will', 'Joe', 'Will'], dtype='<U11')

In [ ]:
array_3 = np.array([5,9,0])

In [ ]:
np.multiply(array_1,array_2)

array([12, 27, 16, 36])

In [ ]:
random_array = np.random.randn(7,4)
random_array

array([[ 0.38961864,  2.77638385, -1.25346882,  1.44035784],
       [-0.25561472,  0.49378969,  0.78300572,  0.69146072],
       [-0.32077979,  0.25054495,  2.10486665, -2.04570812],
       [-0.87736506,  0.05499339,  0.31188992, -0.02092252],
       [ 0.00832022, -0.53396002, -1.13380635, -0.12152569],
       [ 0.79818875,  2.29382137, -0.22267448,  0.83734833],
       [-0.15736897,  0.20581568,  1.01390875, -0.27826121]])

In [ ]:
np.ceil(random_array)

array([[ 1.,  3., -1.,  2.],
       [-0.,  1.,  1.,  1.],
       [-0.,  1.,  3., -2.],
       [-0.,  1.,  1., -0.],
       [ 1., -0., -1., -0.],
       [ 1.,  3., -0.,  1.],
       [-0.,  1.,  2., -0.]])

In [ ]:
np.floor(random_array)

array([[ 0.,  2., -2.,  1.],
       [-1.,  0.,  0.,  0.],
       [-1.,  0.,  2., -3.],
       [-1.,  0.,  0., -1.],
       [ 0., -1., -2., -1.],
       [ 0.,  2., -1.,  0.],
       [-1.,  0.,  1., -1.]])

In [ ]:
Array = np.random.randn(4,2)
Array

array([[-1.54469464,  1.15444903],
       [-0.74185601,  0.01185844],
       [ 0.34248745,  2.24369313],
       [ 0.82485518, -0.15143142]])

In [ ]:
Array.mean()

0.26742014611954745

In [ ]:
Array.std()

1.0927025473978205

In [ ]:
Array.var()

1.1939988570896862

In [ ]:
Array.min()

-1.5446946399479962

In [ ]:
Array.max()

2.243693131778845

In [ ]:
np.save("My_array.npy",Array)


In [ ]:
Array_new = np.load("My_array.npy")

In [ ]:
Data_1 = np.array([1,3,9,12,18])
Data_2 = np.array([[1,5,2,0],[3,6,4,7]])
Data_3 = np.array([['7','6'],['5','4'],['3','2']])
Data_4 = np.array([[11,52,20,50],[34,61,43,17]])


In [ ]:
Data_1

array([ 1,  3,  9, 12, 18])

In [ ]:
Data_2

array([[1, 5, 2, 0],
       [3, 6, 4, 7]])

In [ ]:
Data_3

array([['7', '6'],
       ['5', '4'],
       ['3', '2']], dtype='<U1')

In [ ]:
Data_4

array([[11, 52, 20, 50],
       [34, 61, 43, 17]])

In [ ]:
Data_1 + Data_1

array([ 2,  6, 18, 24, 36])

In [ ]:
np.add(Data_1,Data_1)

array([ 2,  6, 18, 24, 36])

In [ ]:
Data_1 * 10 # Broadcast

array([ 10,  30,  90, 120, 180])

In [ ]:
Data_1.dtype

dtype('int32')

In [ ]:
Data_2.dtype

dtype('int32')

In [ ]:
Data_3.dtype

dtype('<U1')

In [ ]:
Data_4.dtype

dtype('int32')

In [ ]:
Data_3 = np.array(Data_3,dtype = 'int32')

In [ ]:
zeros_array = np.zeros((3,5))
zeros_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
ones_array = np.ones((2,8))
ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
rand_arr = np.random.randn(6,3)
rand_arr

array([[ 0.44105932,  1.24701116, -0.24783342],
       [ 0.24493891, -0.09769475,  1.20676545],
       [ 0.24818501,  0.38919334, -0.65670032],
       [-1.231823  ,  1.03808864, -2.46217454],
       [ 0.70354933, -0.84583917, -0.56826625],
       [-0.17956472, -0.01797633, -0.77137194]])

In [ ]:
rand_arr = np.array(rand_arr ,dtype = 'int64')
rand_arr

array([[ 0,  1,  0],
       [ 0,  0,  1],
       [ 0,  0,  0],
       [-1,  1, -2],
       [ 0,  0,  0],
       [ 0,  0,  0]], dtype=int64)

In [ ]:
 Data_1[2] = 81
 Data_1[4] =144

In [ ]:
Data_1

array([  1,   3,  81,  12, 144])

In [ ]:
Data_2[0][1] =25
Data_2[1][2] = 16


In [ ]:
Data_2

array([[ 1, 25,  2,  0],
       [ 3,  6, 16,  7]])

In [ ]:
Subjects = np.array([['ML','OS','CCN'],['OS','AI','MP'],['CCN','ML','AI']])
Subjects

array([['ML', 'OS', 'CCN'],
       ['OS', 'AI', 'MP'],
       ['CCN', 'ML', 'AI']], dtype='<U3')

In [ ]:
Courses = (Subjects == 'ML') | (Subjects =='AI') # In numpy | is or operator and & is and operator.

In [ ]:
Courses

array([[ True, False, False],
       [False,  True, False],
       [False,  True,  True]])

In [ ]:
Data_1.shape

(5,)

In [ ]:
Data_1.reshape(1,5)

array([[  1,   3,  81,  12, 144]])

In [ ]:
Data_2.shape

(2, 4)

In [ ]:
Data_2.reshape(4,2)

array([[ 1, 25],
       [ 2,  0],
       [ 3,  6],
       [16,  7]])

In [ ]:
Data_2.transpose()

array([[ 1,  3],
       [25,  6],
       [ 2, 16],
       [ 0,  7]])

In [ ]:
Data_3.transpose()

array([[7, 5, 3],
       [6, 4, 2]])

In [ ]:
Data_4.transpose()

array([[11, 34],
       [52, 61],
       [20, 43],
       [50, 17]])