In [1]:
# Aggregiation:
class Publication:
    def get_data(self):
        self.title = input("Enter a title: ")
        self.price = float(input("Enter a price: "))
    def put_data(self):
        print('Title:',self.title)
        print('Price:',self.price)

In [2]:
class Sales:
    def get_data(self):
        month1 = float(input("Enter sales amount for month 1: "))
        month2 = float(input("Enter sales amount for month 2: "))
        month3 = float(input("Enter sales amount for month 3: "))
        self.sales = [month1,month2,month3]
        
    def put_data(self):
        print('Sales of 3 Months: ',self.sales)

In [5]:
class Book(Publication ):
    def get_data(self,sale):
        sale.get_data()
        Publication.get_data(self)
        self.page_count = int(input(("Enter page count: ")))
        
    def put_data(self,sale):
        sale.put_data()
        Publication.put_data(self)
        print("Page Count:",self.page_count)

In [6]:
# Aggregiation:
sale1 = Sales() # sale class
book1 = Book() # book class
book1.get_data(sale1)

In [7]:
book1.put_data(sale1)

Sales of 3 Months:  [560.0, 800.0, 798.0]
Title: xyz
Price: 500.0
Page Count: 300


In [8]:
class A:
    def __init__(self,v):
        self.varA = v

class B:
    def __init__(self,x,y):
        self.varB1 = x
        self.varB2 = y

        

In [9]:
a = A(5)
b = B(6,a)
b.varB1

6

In [10]:
b.varB2.varA

5

In [11]:
# composition:
class Publication:
    def get_data(self):
        self.title = input("Enter a title: ")
        self.price = float(input("Enter a price: "))
    def put_data(self):
        print('Title:',self.title)
        print('Price:',self.price)

In [16]:
class Book(Publication ):
    def get_data(self):
        self.sale = Sales() # sales class object
        self.sale.get_data()
        Publication.get_data(self)
        self.page_count = int(input(("Enter page count: ")))
        
    def put_data(self):
        self.sale.put_data()
        Publication.put_data(self)
        print("Page Count:",self.page_count)

In [19]:
book1 = Book()
book1.get_data()

In [20]:
book1.put_data()

Sales of 3 Months:  [678.0, 678.0, 657.0]
Title: abc123
Price: 670.0
Page Count: 568


In [21]:
class A:
    def __init__(self,v):
        self.varA = v

class B:
    def __init__(self,x):
        self.varB1 = x
        self.varB2 = A(5)

In [22]:
b = B(77)

In [23]:
b.varB1

77

In [24]:
b.varB2

In [25]:
b.varB2.varA

5

Define a class called BasicSalary having one instance variable basic to store basic salary of an employee. Add
appropriate __init__ method and another method annualBasicSalary which calculates and returns the sum
of basic salaries for twelve months. Now define another class called Employee which instantiates an object of
BasicSalary type in its __init__ method. It also instantiate an instance variable called annualBonus. Add a
method annualNetSalary to Employee which returns the annual net salary of an employee including the annual
basic and annual bonus.Define a class called BasicSalary having one instance variable basic to store basic salary of an employee. Add
appropriate __init__ method and another method annualBasicSalary which calculates and returns the sum
of basic salaries for twelve months. Now define another class called Employee which instantiates an object of
BasicSalary type in its __init__ method. It also instantiate an instance variable called annualBonus. Add a
method annualNetSalary to Employee which returns the annual net salary of an employee including the annual
basic and annual bonus.

In [33]:
class BasicSalary:
    def __init__(self,b):
        self.basic = b
        
    def annual_basic_salary(self):
        salary = 0
        for i in range(12):
            user = float(input('Enter a salary: '))
            salary = salary + user
            
            self.basic_salary = salary
            return self.basic_salary

In [34]:
class Employee:
    def __init__(self,ab):
        self.annual_bonus = ab
        self.basic_salary = BasicSalary(1000) # Object
        
    def annual_net_salary(self):
      annual_salary = self.basic_salary.annual_basic_salary()
      annual_net_salary = (annual_salary / 12) + self.annual_bonus + self.basic_salary.basic
      print(annual_net_salary)
        

In [36]:
e1 = Employee(3000)
e1.annual_net_salary()

4016.6666666666665


Define a class called Point that stores two coordinates of a 2D point. Add appropriate methods including initiator,
__str__ and setters. Add any other method if you want to.


In [71]:
class Point:
    def __init__(self,x,y):
        self.x = x
        self.y = y
    
    def __str__(self):  
       return str(('X-Coordinate:' , self.x , 'Y-Coordinate: ',self.y ))
    
    def setter(self,x,y):
        self.x = x
        self.y =y

In [2]:
p1 = Point(4,5)

In [3]:
print(p1)

('X-Coordinate:', 4, 'Y-Coordinate: ', 5)


In [38]:
class Distance:
    def __init__(self):
        self.p1 = Point(5,8)
        self.p2 = Point(2,6)
        
    def setter(self,p1,p2):
        self.p1 = p1
        self.p2 = p2
        
    def findDistance(self):
        self.dis = ((self.p1.x - self.p2.x)**2 + (self.p1.y - self.p2.y)**2)**0.5
        print('Distance: ', self.dis)
        
    def __sub__(self,d2):
        dist = self.dis - d2.dis
        return dist
    def __add__(self,d2):
        dist = self.dis + d2.dis
        return dist
    def __mul__(self,d2):
        dist = self.dis * d2.dis
        return dist
    def __truediv__(self,d2):
        dist = self.dis / d2.dis
        return dist

In [39]:
d1 = Distance()
d1.findDistance()

Distance:  3.605551275463989


In [40]:
#Aggregiation
point1 = Point(9,6)
point2 = Point(8,2)
d1.setter(point1,point2)
d1.findDistance()

Distance:  4.123105625617661


In [41]:
d2 = Distance()
p1 = Point(5,2)
p2 = Point(6,4)
d2.setter(p1,p2)
d2.findDistance()


Distance:  2.23606797749979


In [42]:
d1 - d2

1.8870376481178708

In [43]:
d1 + d2

6.35917360311745

In [44]:
d1 * d2

9.219544457292887

In [45]:
d1/d2

1.8439088914585773

In [72]:
class Polygon:
    def __init__(self):
        self.lop = []
    
    def addPoint(self,lop):
        self.lop = lop
        
    
    @staticmethod
    def distance(x1,x2):
        dist = ((x1.x - x2.x)**2 + (x1.y - x2.y)**2)**0.5
        return dist
    
    def perimeter(self):
        value_dis = 0
        for i in range(len(self.lop)):
            if i != (len(self.lop)-1):
                dis_meth = Polygon.distance(self.lop[i],self.lop[i+1])
                value_dis = dis_meth + value_dis
            else:
                dis_meth = Polygon.distance(self.lop[i],self.lop[0])
                value_dis = dis_meth + value_dis
        return value_dis
                
                
                

In [73]:
square = Polygon()
p1 = Point(9,8)
p2 = Point(7,4)
p3 = Point(6,2)
p4 = Point(5,1)
square.addPoint([p1, p2, p3, p4])
square.perimeter()

16.184675243171014

In [74]:
hexagon = Polygon()
p1 = Point(4,3)
p2 = Point(8,3)
p3 = Point(7,4)
p4 = Point(5,2)
p5 = Point(7,5)
p6 = Point(9,3)
hexagon.addPoint([p1, p2, p3, p4, p5, p6])
hexagon.perimeter()

19.676619087329463

In [75]:
square = Polygon()
p1 = Point(1,1)
p2 = Point(1,2)
p3 = Point(2,2)
p4 = Point(2,1)
square.addPoint([p1, p2, p3, p4])
square.perimeter()

4.0

In [76]:
triangle = Polygon()
p1 = Point(1,0)
p2 = Point(2,2)
p3 = Point(3,0)
triangle.addPoint([p1, p2, p3])
triangle.perimeter()

6.47213595499958

In [77]:
pentagon = Polygon()
p1 = Point(2,2)
p2 = Point(3,3)
p3 = Point(6,4)
p4 = Point(5,2)
p5 = Point(4,0)
pentagon.addPoint([p1, p2, p3, p4,p5])
pentagon.perimeter()

11.877054302287243

In [1]:
import numpy as np

In [2]:
list1 = [1,2,3,4,5,6]
list2 = [7,6,8,9,1,5]
list3 = []
for i in range(len(list1)):
    add = list1[i] + list2[i]
    list3.append(add)
print(list3)

[8, 8, 11, 13, 6, 11]


In [6]:
array1 = np.array(list1)
array2 = np.array(list2)
array4 = np.array([88,45,23,21,55,27])
array3 = array1 + array2 + array4
array3

array([96, 53, 34, 34, 61, 38])

In [7]:
# shape (rows,columns)

array1.shape

(6,)

In [8]:
my_array = np.array(([1,3,5,6,7],[6,9,6,8,5]))
my_array.shape

(2, 5)

In [9]:
array1.ndim

1

In [10]:
my_array.ndim

2

In [12]:
array1.dtype

dtype('int32')

In [16]:
array4 = np.array([88,45,23,21,55,27], dtype=np.float32)
array4.dtype

dtype('float32')

In [17]:
array4

array([88., 45., 23., 21., 55., 27.], dtype=float32)

In [18]:
zero_array = np.zeros((4,6))
zero_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
zero_array.ndim

2

In [20]:
random_array = np.arange(12)
random_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
reshape_array = random_array.reshape(6,2)

In [23]:
reshape_array.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [24]:
reshape_array.reshape(12,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])