In [1]:
import numpy as np

In [2]:
list1 = [1,2,3,4,5,6]
list2 = [7,6,8,9,1,5]
list3 = []
for i in range(len(list1)):
    add = list1[i] + list2[i]
    list3.append(add)
print(list3)

[8, 8, 11, 13, 6, 11]


In [3]:
array1 = np.array(list1)
array2 = np.array(list2)
array4 = np.array([88,45,23,21,55,27])
array3 = array1 + array2 + array4
array3

array([96, 53, 34, 34, 61, 38])

In [4]:
# shape (rows,columns)

array1.shape

(6,)

In [5]:
my_array = np.array(([1,3,5,6,7],[6,9,6,8,5]))
my_array.shape

(2, 5)

In [6]:
array1.ndim

1

In [7]:
my_array.ndim

2

In [8]:
array1.dtype

dtype('int32')

In [9]:
array4 = np.array([88,45,23,21,55,27], dtype=np.float32)
array4.dtype

dtype('float32')

In [10]:
array4

array([88., 45., 23., 21., 55., 27.], dtype=float32)

In [11]:
zero_array = np.zeros((4,6))
zero_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
zero_array.ndim

2

In [13]:
random_array = np.arange(12)
random_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
reshape_array = random_array.reshape(6,2)

In [15]:
reshape_array.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [16]:
reshape_array.reshape(12,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
ones_array = np.ones((3,9))
ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [18]:
new_arr = np.arange(20)
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
new_arr[5]

5

In [20]:
my_arr = np.array([89,45,23,55,23,98,10,55])
my_arr[5]

98

In [21]:
my_arr[2:6]

array([23, 55, 23, 98])

In [22]:
my_arr[5] = 456

In [23]:
my_arr

array([ 89,  45,  23,  55,  23, 456,  10,  55])

In [24]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
new_arr *5 #Broadcasting

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [26]:
new_arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21])

In [27]:
two_arr = np.array(([23,45,56],[34,67,92]))
two_arr

array([[23, 45, 56],
       [34, 67, 92]])

In [28]:
two_arr *0

array([[0, 0, 0],
       [0, 0, 0]])

In [29]:
random_array = np.random.randn(4,3)
random_array

array([[ 0.861314  ,  0.67972131,  1.25184132],
       [ 0.8670408 ,  1.95606757, -0.91951435],
       [ 0.50363649,  1.4804127 , -1.49295566],
       [ 1.75875942, -0.05779364, -1.69659381]])

In [30]:
# boolean Indexing
data = np.array(['Bob','Joe','Will','Bob','Joe','Will','Joe','Will'])
data

array(['Bob', 'Joe', 'Will', 'Bob', 'Joe', 'Will', 'Joe', 'Will'],
      dtype='<U4')

In [31]:
data == 'Bob'

array([ True, False, False,  True, False, False, False, False])

In [32]:
data == 'Joe'

array([False,  True, False, False,  True, False,  True, False])

In [33]:
random_array >= 1

array([[False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False]])

In [34]:
# Fancy Indexing
empt_arr = np.empty((8,4), dtype = '<U4')
empt_arr

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U4')

In [35]:
for i in range(8):
    empt_arr[i] = data[i]

In [36]:
empt_arr

array([['Bob', 'Bob', 'Bob', 'Bob'],
       ['Joe', 'Joe', 'Joe', 'Joe'],
       ['Will', 'Will', 'Will', 'Will'],
       ['Bob', 'Bob', 'Bob', 'Bob'],
       ['Joe', 'Joe', 'Joe', 'Joe'],
       ['Will', 'Will', 'Will', 'Will'],
       ['Joe', 'Joe', 'Joe', 'Joe'],
       ['Will', 'Will', 'Will', 'Will']], dtype='<U4')

In [37]:
#concatenation
array_1 = np.array([2,3,4,6])
array_2 = np.array([6,9,4,6])
array_1

array([2, 3, 4, 6])

In [38]:
array_2

array([6, 9, 4, 6])

In [39]:
np.concatenate([array_1,array_2, data])

array(['2', '3', '4', '6', '6', '9', '4', '6', 'Bob', 'Joe', 'Will',
       'Bob', 'Joe', 'Will', 'Joe', 'Will'], dtype='<U11')

In [40]:
array_3 = np.array([5,9,0])

In [41]:
np.multiply(array_1,array_2)

array([12, 27, 16, 36])

In [42]:
random_array = np.random.randn(7,4)
random_array

array([[-0.557585  ,  1.08508862,  1.6045848 ,  1.31502277],
       [ 0.49520653,  1.52214283,  0.33696803,  0.13273252],
       [-1.12044633,  1.30308553,  0.69550494,  0.51746084],
       [ 1.19124868, -1.20285737, -0.95755722, -1.02837758],
       [ 1.20235557, -0.05513136,  0.0531365 , -0.29156535],
       [-0.36716154, -1.53161793, -0.65621322,  0.16690844],
       [-0.19125493, -2.0387641 , -1.23224649,  0.09937407]])

In [43]:
np.ceil(random_array)

array([[-0.,  2.,  2.,  2.],
       [ 1.,  2.,  1.,  1.],
       [-1.,  2.,  1.,  1.],
       [ 2., -1., -0., -1.],
       [ 2., -0.,  1., -0.],
       [-0., -1., -0.,  1.],
       [-0., -2., -1.,  1.]])

In [44]:
np.floor(random_array)

array([[-1.,  1.,  1.,  1.],
       [ 0.,  1.,  0.,  0.],
       [-2.,  1.,  0.,  0.],
       [ 1., -2., -1., -2.],
       [ 1., -1.,  0., -1.],
       [-1., -2., -1.,  0.],
       [-1., -3., -2.,  0.]])